version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  publish-dev-and-promote:
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: noyo/gcp-npm
          context: orb-publishing # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: noyo/gcp-npm
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only:
                - main
